#!/bin/bash
#example elsa module
set -e
echo hello world
function get_value(){
    echo $(eval echo "\${main_${1}_test}")
}

for e in $(get_value feature) ; do
    echo "ITEM:" $e
done
echo "### ENVS ###"
env | sort
