#!/bin/bash
## example configuration
# empty

set -e
total=$(df -i /source | tr -s " " | cut -f2 -d" " | tail -n 1)
count=0
percent_last=""
cp -prvf /source/. /target/ |& while read line ; do
    count=$(($count+1))
    percent=$((($count*1000)/total))
    if [[ "${percent_last}" != "$percent" ]] ; then
        echo "STATUS:name=copy:percent=$percent"
        percent_last=$percent
    fi
done
echo "STATUS:name=sync"
sync

