#!/bin/bash
## Example Configuration
# [grub]
# device=sda
# type=x86_64-efi
# update=true

set -e

for dir in dev sys proc run ; do
    mount --bind /$dir /target/"$dir"
done

if [[ -d /sys/firmware/efi/ ]] ; then
    mount -t efivarfs efivarfs /target/sys/firmware/efi/efivars
    mkdir -p /target/boot/efi
fi

echo "STATUS:name=grub:device=${grub_device}:type=${grub_type}"
chroot /target grub-install --removable \
    --target="${grub_type}" /dev/"${grub_device}"
if [[ "${grub_update}" == true ]] ; then
    chroot /target grub-mkconfig -o /boot/grub/grub.cfg
fi

if [[ -d /sys/firmware/efi/ ]] ; then
    umount -lf /target/sys/firmware/efi/efivars
fi

for dir in dev sys proc run ; do
    umount -lf /target/"$dir"
done
sync

