#!/bin/bash
## example configuration
# [partition]
# parts=sda
# [partition_sda]
# table=gpt
# create=2
# [partition_sda1]
# begin=2048s
# size=100M
# type=vfat
# [partition_sda2]
# begin=100m
# size=100%
# type=ext4

set -e
function get_value(){
    echo $(eval echo "\${partition_${1}}")
}
for disk in ${partition_parts[@]} ; do
    head -c 512 /dev/zero > /dev/"$disk"
    table=$(get_value "$disk"_table)
    echo "STATUS:name=mktable:disk=/dev/$disk:type=$table"
    parted -s /dev/"$disk" mklabel "$table"
    create=$(get_value  "$disk"_create)
    for part in $(eval echo {1..$create}) ; do
        part="$disk""$part"
        begin=$(get_value "$part"_begin)
        size=$(get_value "$part"_size)
        type=$(get_value "$part"_type)
        echo "STATUS:name=mkpart:disk=/dev/$part:type=$type:size=$size"
        parted -s /dev/"$disk" mkpart primary "$begin" "$size"
        sync
        mkfs."$type" /dev/"$part"
        sync
    done
done

