#!/bin/bash
## example configuration
# empty
set -e
mount | grep " /target" | cut -f3 -d" " | sort -V -r | while read dir ; do
    umount -lf "$dir"
done
if mount | grep " /source" >/dev/null ; then
    umount -lf /source
fi

